version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "dependencies"
    ignore:
      # ignoring https://github.com/duckduckgo/privacy-configuration for now
      - dependency-name: 'config-builder'
        versions: ['*']
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
