name: Release

on:
  workflow_dispatch:

jobs:
  release_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Fetch files and checkout
        run: |
          git fetch --all
          git checkout releases

      - name: Build release
        run: |
          npm install
          npm run build

      - name: Check in files
        run: |
          git add -f build/ Sources/

      - name: Commit build files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Release build [ci release]"
          commit_options: '--allow-empty'
          branch: "releases"

      - name: Ship
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx auto shipit
